services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test_db.sqlite
      - JWT_SECRET_KEY=test-secret-key-for-docker
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost:8501
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    volumes:
      - ./test_uploads:/app/uploads

networks:
  rag-network:
    driver: bridge

volumes:
  test_uploads: 