services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test_db.sqlite
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=test-secret-key-for-docker
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost:8501
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    volumes:
      - ./test_uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    depends_on:
      - backend
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rag-network:
    driver: bridge

volumes:
  test_uploads: 